ProductPromotion/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProductPromotion.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly ICartRepository _cartRepository;

        public IndexModel(IProductRepository productRepository, ICartRepository cartRepository)
        {
            _productRepository = productRepository;
            _cartRepository = cartRepository;
        }

        public IEnumerable<Entities.Product> ProductList { get; set; } = new List<Entities.Product>();

        public async Task<IActionResult> OnGetAsync()
        {
            ProductList = await _productRepository.GetProducts();
            return Page();
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            await _cartRepository.AddItem("test", productId);
            return RedirectToPage("Cart");
        }
    }
}

ProductPromotion/Pages/Shared/_ContactUsPartial.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProductPromotion.Pages.Shared
{
    public class _ContactUsPartialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ProductPromotion/Pages/Shared/_LoginPartial.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProductPromotion.Pages.Shared
{
    public class _LoginPartialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ProductPromotion/Pages/Shared/_Navbar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ProductPromotion.Entities;
using ProductPromotion.Repositories;
using ProductPromotion.Repositories.Interfaces;
using System.Threading.Tasks;

namespace ProductPromotion.Pages.Shared
{
    public class _NavbarModel : PageModel
    {
    }
}

ProductPromotion/Pages/Shared/_ContactUsPartial.cshtml
@{
}

<div class="card">
    <div class="card-body">
        <h2>Bizimle İletişime Geçin</h2>
        <img style="width: 75%; margin: 0 auto; display: block;" src="~/images/placeholder.png" />
        <p>Soru ve geri bildirimleriniz için iletişime geçin.</p>
    </div>
    <div class="card-footer">
        <a asp-area="" asp-page="/Contact" class="btn btn-outline-success">Bizimle İletişime Geçin</a>
    </div>
</div>

ProductPromotion/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - ProductPromotion</title>

    <!-- CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600" rel="stylesheet" type="text/css">
    <link href="css/style.css" rel="stylesheet" type="text/css">

</head>
<body>
    <header>
        <partial name="_Navbar"/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer -->
    <footer class="text-light">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-lg-4 col-xl-3">
                    <h5>Hakkımızda</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <p class="mb-0">
                        Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
                    </p>
                </div>

                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
                    <h5>Bilgilendirme</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <ul class="list-unstyled">
                        <li><a href="">Link 1</a></li>
                        <li><a href="">Link 2</a></li>
                        <li><a href="">Link 3</a></li>
                        <li><a href="">Link 4</a></li>
                    </ul>
                </div>

                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                    <h5>Site Haritası</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <ul class="list-unstyled">
                        <li><a href="">Link 1</a></li>
                        <li><a href="">Link 2</a></li>
                        <li><a href="">Link 3</a></li>
                        <li><a href="">Link 4</a></li>
                    </ul>
                </div>

                <div class="col-md-4 col-lg-3 col-xl-3">
                    <h5>İletişim</h5>
                    <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                    <ul class="list-unstyled">
                        <li><i class="fa fa-home mr-2"></i> Şirketimiz</li>
                        <li><i class="fa fa-envelope mr-2"></i> email@example.com</li>
                        <li><i class="fa fa-phone mr-2"></i> + 90 500 000 00 00</li>
                        <li><i class="fa fa-print mr-2"></i> + 90 500 000 00 00</li>
                    </ul>
                </div>
                <div class="col-12 copyright mt-3">
                    <p class="float-left">
                        <a href="#" class="btn btn-outline-secondary">Yukarı Çık</a>
                    </p>
                    <p class="text-right text-muted">Yayınlayan | by İbrahim</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="//code.jquery.com/jquery-3.2.1.slim.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            var quantity = 1;
            $('.quantity-right-plus').click(function (e) {
                e.preventDefault();
                var quantity = parseInt($('#quantity').val());
                $('#quantity').val(quantity + 1);
            });
            $('.quantity-left-minus').click(function (e) {
                e.preventDefault();
                var quantity = parseInt($('#quantity').val());
                if (quantity > 1) {
                    $('#quantity').val(quantity - 1);
                }
            });
        });

        (function () {
            'use strict';
            window.addEventListener('load', function () {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ProductPromotion/Pages/Shared/_MobileWidgetPartial.cshtml
@model string

<div class="card">
    <div class="card-body">
        <h2>@Model</h2>
        <div class="description">
            <p>İndirimlerden haberdar olmak için takipte kalın</p>
            <ul>
                <li>Kuponlar ve promosyonlar</li>
                <li>Size özel indirimler</li>
            </ul>
        </div>
        <img class="img-fluid rounded" src="~/images/download-small.png" alt="">
    </div>
    <div class="card-footer">
        <a href="#" class="btn btn-outline-success">İndir</a>
    </div>
</div>

ProductPromotion/Pages/Shared/_Navbar.cshtml
@{
}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-page="/Index">Ürün Satış</a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-page="/Index">Anasayfa <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-page="/Product">Ürünler</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-page="/Cart">Sepet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-page="/Order">Siparişler</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-page="/Contact">İletişim</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" placeholder="Arayınız...">
                    <div class="input-group-append">
                        <button type="button" class="btn btn-outline-secondary btn-number">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
                <a class="btn btn-success btn-sm ml-3" asp-area="" asp-page="/Cart">
                    <i class="fa fa-shopping-cart"></i> Sepet
                    <span class="badge badge-light">1</span>
                </a>
            </form>
        </div>
    </div>
</nav>

ProductPromotion/Pages/Shared/_ProductItemPartial.cshtml
@model Product

<div class="card">
    <a asp-page="ProductDetail" asp-route-productId="@Model.Id"><img asp-append-version="true" class="card-img-top" src="~/images/product/@Model.ImageFile" alt=""></a>
    <div class="card-body">
        <h4 class="card-title"><a asp-page="ProductDetail" asp-route-productId="@Model.Id" class="color-main">@Model.Name</a></h4>
        <p class="card-text">@Model.Summary</p>
        <div class="row">
            <div class="col">
                <p class="btn btn-outline-danger btn-block">@Model.Price ₺</p>
            </div>
            <div class="col">
                <form asp-page-handler="AddToCart" method="post" name="addToCartForm" id="add_cart_form">
                    <a href="javascript:;" onclick="parentNode.submit();" class="btn btn-outline-success btn-block">Sepete Ekle</a>
                    <input type="hidden" asp-for="@Model.Id" name="productId" />
                </form>
            </div>
        </div>
    </div>
</div>

ProductPromotion/Pages/Shared/_TopProductPartial.cshtml
@model Product

<div class="col-12 col-md-3">
    <div class="card">
        <div class="card-header bg-success text-white text-uppercase">
            <i class="fa fa-heart"></i> En İyi Ürünler
        </div>
        <a asp-page="ProductDetail" asp-route-productId="@Model.Id"><img asp-append-version="true" class="img-fluid border-0" src="~/images/product/@Model.ImageFile" alt="Card image cap"></a>
        <div class="card-body">
            <h4 class="card-title text-center"><a asp-page="ProductDetail" asp-route-productId="@Model.Id" title="Ürün Görüntüle">@Model.Name</a></h4>
            <div class="row">
                <div class="col">
                    <p class="btn btn-outline-danger btn-block">@Model.Price ₺</p>
                </div>
                <div class="col">
                    <a asp-page="ProductDetail" asp-route-productId="@Model.Id" class="btn btn-outline-success btn-block">Görüntüle</a>
                </div>
            </div>
        </div>
    </div>
</div>