ProductPromotion/Entities/Cart.cs
using System.Collections.Generic;

namespace ProductPromotion.Entities
{
    public class Cart
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public List<CartItem> Items { get; set; } = new List<CartItem>();

        public decimal TotalPrice
        {
            get
            {
                decimal totalprice = 0;
                foreach (var item in Items)
                {
                    totalprice += item.Price * item.Quantity;
                }

                return totalprice;
            }
        }
    }
}

ProductPromotion/Entities/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ProductPromotion.Entities
{
    public class Category
    {
        public int Id { get; set; }

        [Required, StringLength(80)]
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
    }
}

ProductPromotion/Entities/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace ProductPromotion.Entities
{
    public class Contact
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Phone]
        [Required]
        public string Phone { get; set; }

        [Required]
        public string Email { get; set; }

        [MinLength(10)]
        [Required]
        public string Message { get; set; }
    }
}

ProductPromotion/Entities/Order.cs
namespace ProductPromotion.Entities
{
    public class Order
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public decimal TotalPrice { get; set; }

        // BillingAddress
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string AddressLine { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }

        // Payment
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string Expiration { get; set; }
        public string CVV { get; set; }
        public PaymentMethod PaymentMethod { get; set; }
    }

    public enum PaymentMethod
    {
        CreditCard = 1,
        DebitCard = 2,
        Paypal = 3
    }
}

ProductPromotion/Entities/Product.cs
using System.ComponentModel.DataAnnotations;

namespace ProductPromotion.Entities
{
    public class Product
    {
        public int Id { get; set; }

        [Required, StringLength(80)]
        public string Name { get; set; }

        public string Summary { get; set; }
        public string Description { get; set; }

        public string ImageFile { get; set; }
        public decimal Price { get; set; }

        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

ProductPromotion/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Entities;
using ProductPromotion.Repositories.Interfaces;
using System.Threading.Tasks;
using System;

namespace ProductPromotion
{
    public class CartModel : PageModel
    {
        private readonly ICartRepository _cartRepository;

        public CartModel(ICartRepository cartRepository)
        {
            _cartRepository = cartRepository;
        }

        public Entities.Cart Cart { get; set; } = new Entities.Cart();


        public async Task<IActionResult> OnGetAsync()
        {
            Cart = await _cartRepository.GetCartByUserName("test");

            return Page();
        }

        public async Task<IActionResult> OnPostRemoveToCartAsync(int cartId, int cartItemId)
        {
            await _cartRepository.RemoveItem(cartId, cartItemId);
            return RedirectToPage();
        }
    }
}

ProductPromotion/Pages/Category.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using ProductPromotion.Repositories.Interfaces;

namespace ProductPromotion
{
    public class CategoryModel : PageModel
    {
        private readonly IProductRepository _productRepository;

        public CategoryModel(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IEnumerable<Entities.Category> CategoryList { get; set; } = new List<Entities.Category>();

        public async Task<IActionResult> OnGetAsync()
        {
            CategoryList = await _productRepository.GetCategories();
            return Page();
        }
    }
}

ProductPromotion/Pages/Category/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace ProductPromotion.Pages.Category
{
    public class IndexModel : PageModel
    {
        private readonly IProductRepository _productRepository;

        public IndexModel(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IEnumerable<Entities.Category> CategoryList { get; set; } = new List<Entities.Category>();

        public async Task<IActionResult> OnGetAsync()
        {
            CategoryList = await _productRepository.GetCategories();
            return Page();
        }
    }
}

ProductPromotion/Pages/CheckOut.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories.Interfaces;
using System.Threading.Tasks;
using System;

namespace ProductPromotion
{
    public class CheckOutModel : PageModel
    {
        private readonly ICartRepository _cartRepository;
        private readonly IOrderRepository _orderRepository;

        public CheckOutModel(ICartRepository cartRepository, IOrderRepository orderRepository)
        {
            _cartRepository = cartRepository;
            _orderRepository = orderRepository;
        }

        [BindProperty]
        public Entities.Order Order { get; set; }

        [BindProperty]
        public Entities.Cart Cart { get; set; } = new Entities.Cart();

        public async Task<IActionResult> OnGetAsync()
        {
            Cart = await _cartRepository.GetCartByUserName("test");
            return Page();
        }

        public async Task<IActionResult> OnPostCheckOutAsync()
        {
            Cart = await _cartRepository.GetCartByUserName("test");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            Order.UserName = "test";
            Order.TotalPrice = Cart.TotalPrice;

            await _orderRepository.CheckOut(Order);
            await _cartRepository.ClearCart("test");

            return RedirectToPage("Confirmation", "OrderSubmitted");
        }
    }
}

ProductPromotion/Pages/Confirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProductPromotion
{
    public class ConfirmationModel : PageModel
    {
        public string Message { get; set; }

        public void OnGetContact()
        {
            Message = "Your email was sent.";
        }

        public void OnGetOrderSubmitted()
        {
            Message = "Your order submitted successfully.";
        }
    }
}

ProductPromotion/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Entities;
using ProductPromotion.Repositories.Interfaces;
using System.Threading.Tasks;

namespace ProductPromotion
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ProductPromotion/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProductPromotion.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ProductPromotion/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProductPromotion.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly ICartRepository _cartRepository;

        public IndexModel(IProductRepository productRepository, ICartRepository cartRepository)
        {
            _productRepository = productRepository;
            _cartRepository = cartRepository;
        }

        public IEnumerable<Entities.Product> ProductList { get; set; } = new List<Entities.Product>();

        public async Task<IActionResult> OnGetAsync()
        {
            ProductList = await _productRepository.GetProducts();
            return Page();
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            await _cartRepository.AddItem("test", productId);
            return RedirectToPage("Cart");
        }
    }
}

ProductPromotion/Pages/Order.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace ProductPromotion
{
    public class OrderModel : PageModel
    {
        private readonly IOrderRepository _orderRepository;

        public OrderModel(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }

        public IEnumerable<Entities.Order> Orders { get; set; } = new List<Entities.Order>();

        public async Task<IActionResult> OnGetAsync()
        {
            Orders = await _orderRepository.GetOrdersByUserName("test");

            return Page();
        }
    }
}

ProductPromotion/Pages/Product.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProductPromotion
{
    public class ProductModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly ICartRepository _cartRepository;

        public ProductModel(IProductRepository productRepository, ICartRepository cartRepository)
        {
            _productRepository = productRepository;
            _cartRepository = cartRepository;
        }

        public IEnumerable<Entities.Category> CategoryList { get; set; } = new List<Entities.Category>();
        public IEnumerable<Entities.Product> ProductList { get; set; } = new List<Entities.Product>();


        [BindProperty(SupportsGet = true)]
        public string SelectedCategory { get; set; }

        public async Task<IActionResult> OnGetAsync(int? categoryId)
        {
            CategoryList = await _productRepository.GetCategories();

            if (categoryId.HasValue)
            {
                ProductList = await _productRepository.GetProductByCategory(categoryId.Value);
                SelectedCategory = CategoryList.FirstOrDefault(c => c.Id == categoryId.Value)?.Name;
            }
            else
            {
                ProductList = await _productRepository.GetProducts();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            await _cartRepository.AddItem("test", productId);
            return RedirectToPage("Cart");
        }
    }
}

ProductPromotion/Pages/Product/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories;
using System.Threading.Tasks;
using System;

namespace ProductPromotion.Pages.Product
{
    public class DetailsModel : PageModel
    {
        private readonly IProductRepository _productRepository;

        public DetailsModel(IProductRepository productRepository)
        {
            _productRepository = productRepository ?? throw new ArgumentNullException(nameof(productRepository));
        }

        public Entities.Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? productId)
        {
            if (productId == null)
            {
                return NotFound();
            }

            Product = await _productRepository.GetProductByIdAsync(productId.Value);
            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ProductPromotion/Pages/ProductDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductPromotion.Repositories.Interfaces;
using System;
using System.Threading.Tasks;

namespace ProductPromotion
{
    public class ProductDetailModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly ICartRepository _cartRepository;

        public ProductDetailModel(IProductRepository productRepository, ICartRepository cartRepository)
        {
            _productRepository = productRepository ;
            _cartRepository = cartRepository ;
        }

        public Entities.Product Product { get; set; }

        [BindProperty]
        public string Color { get; set; }

        [BindProperty]
        public int Quantity { get; set; }

        public async Task<IActionResult> OnGetAsync(int? productId)
        {
            if (productId == null)
            {
                return NotFound();
            }

            Product = await _productRepository.GetProductById(productId.Value);
            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _cartRepository.AddItem("test", productId, Quantity, Color);
            return RedirectToPage("Cart");
        }
    }
}

ProductPromotion/Pages/Cart.cshtml
@page
@model ProductPromotion.CartModel
@{
    ViewData["Title"] = "Cart";
}

<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-page="Index">Anasayfa</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Sepet</li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Ürün</th>
                            <th scope="col">Durum</th>
                            <th scope="col" class="text-center">Miktar</th>
                            <th scope="col" class="text-right">Fiyat</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var cartItem in Model.Cart.Items)
                        {
                            <tr>
                                <td><img src="https://dummyimage.com/50x50/55595c/fff" /></td>
                                <td>@cartItem.Product.Name</td>
                                <td>Stokta</td>
                                <td><input class="form-control" type="text" value="@cartItem.Quantity" /></td>
                                <td class="text-right">@(cartItem.Price * cartItem.Quantity) ₺</td>
                                <td class="text-right">

                                    <form asp-page-handler="removetocart" method="post">
                                        <button class="btn btn-sm btn-outline-danger"><i class="fa fa-trash"></i></button>
                                        <input type="hidden" asp-for="@Model.Cart.Id" name="cartId" />
                                        <input type="hidden" asp-for="@cartItem.Id" name="cartItemId" />
                                    </form>

                                </td>
                            </tr>
                        }

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Toplam</strong></td>
                            <td class="text-right"><strong>@Model.Cart.TotalPrice ₺</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                    <a asp-page="Product" class="btn btn-lg btn-block btn-outline-success">Alışverişe Devam Et</a>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <a asp-page="CheckOut" class="btn btn-lg btn-block btn-outline-danger text-uppercase">Öde</a>
                </div>
            </div>
        </div>
    </div>
</div>

ProductPromotion/Pages/Category.cshtml
@page
@model ProductPromotion.CategoryModel
@{
    ViewData["Title"] = "Categories";
}

<div class="container">
    <h1 class="my-4"></h1>
    <div class="row">
        @foreach (var category in Model.CategoryList)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <div class="card-image bg-@category.ImageName">
                    </div>
                    <div class="card-body">
                        <h2 class="card-title">@category.Name</h2>
                        <p class="card-text">@category.Description</p>
                    </div>
                    <div class="card-footer">
                        <a asp-area="" asp-page="/Product/Index" class="btn btn-outline-success">Bütün Ürünler</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <hr />
    <hr class="mb-5" />
    <div class="row">
        <div class="col-md-4">
            <partial name="_MobileWidgetPartial" model="@("Download Today")" />
        </div>
        <div class="col-md-4">
            <vc:popular-products count="2" />
        </div>
        <div class="col-md-4">
            <partial name="_ContactUsPartial" />
        </div>
    </div>
    <hr class="mb-5">
</div>

ProductPromotion/Pages/CheckOut.cshtml
@page
@model ProductPromotion.CheckOutModel
@{
    ViewData["Title"] = "CheckOut";
}

<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-page="Index">Anasayfa</a></li>
                    <li class="breadcrumb-item"><a asp-page="Cart">Sepet</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Ödeme Sayfası</li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Senin Sepetin</span>
                <span class="badge badge-secondary badge-pill">@Model.Cart.Items.Count</span>
            </h4>
            <ul class="list-group mb-3">

                @foreach (var item in Model.Cart.Items)
                {
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">@item.Product.Name</h6>
                            <small class="text-muted">@item.Product.Summary</small>
                        </div>
                        <span class="text-muted">₺@item.Price</span>
                    </li>
                }

                <li class="list-group-item d-flex justify-content-between">
                    <span>Toplam (TL)</span>
                    <strong>₺@Model.Cart.TotalPrice</strong>
                </li>
            </ul>

            <form class="card p-2">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Promosyon Kodunu Girin">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">Kodu Gir</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Adres</h4>
            <form asp-page-handler="CheckOut" method="post" class="needs-validation" novalidate>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label asp-for="Order.FirstName" for="firstName">Adınız</label>
                        <input asp-for="Order.FirstName" type="text" class="form-control" id="firstName" placeholder="" value="" required>
                        <div class="invalid-feedback">
                            Adınız gereklidir.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label asp-for="Order.LastName" for="lastName">Soyad</label>
                        <input asp-for="Order.LastName" type="text" class="form-control" id="lastName" placeholder="" value="" required>
                        <div class="invalid-feedback">
                            Soyadınız gereklidir.
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="username">Kullanıcı Adı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@@</span>
                        </div>
                        <input type="text" class="form-control" id="username" placeholder="Username" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            Kullanıcı adı gereklidir.
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label asp-for="Order.EmailAddress" for="email">Email</label>
                    <input asp-for="Order.EmailAddress" type="email" class="form-control" id="email" placeholder="email@example.com">
                    <div class="invalid-feedback">
                        Lütfen geçerli bir e-posta adresi giriniz.
                    </div>
                </div>

                <div class="mb-3">
                    <label asp-for="Order.AddressLine" for="address">Adres</label>
                    <input asp-for="Order.AddressLine" type="text" class="form-control" id="address" placeholder="Çiçek mahallesi, 281. sokak" required>
                    <div class="invalid-feedback">
                        Lütfen adresinizi giriniz.
                    </div>
                </div>

                <div class="mb-3">
                    <label for="address2">Bina ve Daire<span class="text-muted"></span></label>
                    <input type="text" class="form-control" id="address2" placeholder="Apartman ve Daire no">
                </div>

                <div class="row">
                    <div class="col-md-5 mb-3">
                        <label asp-for="Order.Country" for="country">Ülke</label>
                        <select asp-for="Order.Country" class="custom-select d-block w-100" id="country" required>
                            <option value="">Seçiniz...</option>
                            <option>Türkiye</option>
                        </select>
                        <div class="invalid-feedback">
                            Lütfen Ülke Seçiniz
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label asp-for="Order.State" for="state">Şehir</label>
                        <select asp-for="Order.State" class="custom-select d-block w-100" id="state" required>
                            <option value="">Seçiniz...</option>
                            <option>İstanbul</option>
                            <option>Ankara</option>
                            <option>İzmir</option>
                            <option>Konya</option>
                        </select>
                        <div class="invalid-feedback">
                            Lütfen Şehir Seçiniz
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label asp-for="Order.ZipCode" for="zip">Posta kodu</label>
                        <input asp-for="Order.ZipCode" type="text" class="form-control" id="zip" placeholder="" required>
                        <div class="invalid-feedback">
                            Posta Kodu Gereklidir.
                        </div>
                    </div>
                </div>
                <hr class="mb-4">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="same-address">
                    <label class="custom-control-label" for="same-address">Gönderim adresi fatura adresim ile aynı</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="save-info">
                    <label class="custom-control-label" for="save-info">Bu bilgiyi bir dahaki sefere sakla</label>
                </div>
                <hr class="mb-4">

                <h4 class="mb-3">Ödeme Yöntemi</h4>

                <div class="d-block my-3">
                    <div class="custom-control custom-radio">
                        <input asp-for="Order.PaymentMethod" id="credit" name="paymentMethod" type="radio" value="Credit card" class="custom-control-input" checked required>
                        <label asp-for="Order.PaymentMethod" class="custom-control-label" for="credit">Kredi Kartı</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input asp-for="Order.PaymentMethod" id="debit" name="paymentMethod" type="radio" value="Debit card" class="custom-control-input" required>
                        <label asp-for="Order.PaymentMethod" class="custom-control-label" for="debit">Banka Kartı</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input asp-for="Order.PaymentMethod" id="paypal" name="paymentMethod" type="radio" value="Paypal" class="custom-control-input" required>
                        <label asp-for="Order.PaymentMethod" class="custom-control-label" for="paypal">Paypal</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label asp-for="Order.CardName" for="cc-name">Kartın üstünde bulunan isim</label>
                        <input asp-for="Order.CardName" type="text" class="form-control" id="cc-name" placeholder="" required>
                        <small class="text-muted">Kartta görüntülendiği şekliyle tam ad</small>
                        <div class="invalid-feedback">
                            Kartın üstünde bulunan isim gereklidir.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label asp-for="Order.CardNumber" for="cc-number">Kart Numarası</label>
                        <input asp-for="Order.CardNumber" type="text" class="form-control" id="cc-number" placeholder="" required>
                        <div class="invalid-feedback">
                            Kart Numarası gereklidir.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <label asp-for="Order.Expiration" for="cc-expiration">Son kullanma tarihi</label>
                        <input asp-for="Order.Expiration" type="text" class="form-control" id="cc-expiration" placeholder="" required>
                        <div class="invalid-feedback">
                            Son kullanma tarihi gereklidir.
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label asp-for="Order.CVV" for="cc-expiration">CVV</label>
                        <input asp-for="Order.CVV" type="text" class="form-control" id="cc-cvv" placeholder="" required>
                        <div class="invalid-feedback">
                            Güvenlik kodu gereklidir.
                        </div>
                    </div>
                </div>
                <hr class="mb-4">
                <button class="btn btn-outline-primary btn-lg btn-block" type="submit">Ödemeye Geç</button>
            </form>
        </div>
    </div>
</div>

ProductPromotion/Pages/Confirmation.cshtml
@page
@model ProductPromotion.ConfirmationModel
@{
    ViewData["Title"] = "Confirmation";
}

<div class="container contact-container">
    <h1 class="mt-4 mb-3">
        Onaylandı
    </h1>
    <hr />
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <h3>@Model.Message</h3>
    }
    <br />
    <p>Başka sorunuz varsa, 500-000-0000 numaralı telefondan bize ulaşabilirsiniz..</p>
</div>

ProductPromotion/Pages/MobileWidget.cshtml
@model string

<div class="card">
    <div class="card-body">
        <h2>@Model</h2>
        <div class="description">
            <p>Stay wired on the go with these benefits:</p>
            <ul>
                <li>Coupons and promotions</li>
                <li>Brainiacs club benefits</li>
                <li>Store locator</li>
                <li>Latest menu options</li>
            </ul>
        </div>
        <img class="img-fluid rounded" src="~/images/download-small.png" alt="">
    </div>
    <div class="card-footer">
        <a href="#" class="btn btn-success">Download</a>
    </div>
</div>